### ISSUE TITLE
Shall we have and what's the maximum size of a message? 

### ISSUE THREAD

**Issue by guanghao479** [guanghao479/HoneyBadger#18]
Shall we have the a maximum size of message? If so, what's it? 

During reading the file content to form a request message, realized it's not feasible to have a message that can contain everything, there are GBytes-ish files, we might have to split apart. 

If we go for the maximum size, besides a constants of maximum size, need an addition to file content message definition, which is serial number.

**Comment by fuj** [comment]
I recall we discussed this already, didn't we? We just didn't get back to
implement this quick enough that we forgot again.

You can hard-code a size in the common header file on server side, or use
something, so that the size of a file can always be checked against
something. Yes each file content message will need a serial number.

On Mon, Jan 9, 2012 at 3:29 AM, fmaj7 <
reply@reply.github.com

**Comment by guanghao479** [comment]
Ah, I sort of recall our discussion. Will do.

Sent from my Windows Phone
